[theme]
name = "Dracula Theme Unofficial"

[theme.base]
white = "#f8f8f2"
black = "#282A35"
grey = "#44475a"
blue = "#61AFEF"
red = "#ff5555"
yellow = "#F4F89B"
orange = "#ffb86c"
green = "#8AF58A"
purple = "#B498F3"
cyan = "#A2E7FA"
magenta = "#E881C0"

[theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#6272a4"
constant = "$cyan"
constructor = "$cyan"
embedded = "$cyan"
enum = "$cyan"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$green"
"function.method" = "$cyan"
interface = "$cyan"
keyword = "$magenta"
method = "$green"
number = "$purple"
property = "$white"
selfKeyword = "$purple"
string = "$yellow"
struct = "$cyan"
structure = "$yellow"
symbol = "$yellow"
type = "$cyan"
"type.builtin" = "$cyan"
typeAlias = "$cyan"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#21252B"
"activity.current" = "$black"
"completion.background" = "#21252B"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "$magenta"
"editor.current_line" = "#313340"
"editor.dim" = "#6272a4"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#21252B"
"inlay_hint.background" = "#528bFF88"
"inlay_hint.foreground" = "$white"
"lapce.active_tab" = "$black"
"lapce.border" = "#191A20"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#21222B"
"palette.current" = "#313340"
"panel.background" = "#21222B"
"panel.current" = "#313340"
"panel.hovered" = "#292A35"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#191A20"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
